### ISSUE TITLE
Metal Theme Contrast 

### ISSUE THREAD

**Issue by thenoobtester** [dhunt84971/CalendarNotes#81]
Hi,

great app, thank you for the time you spent on this. One quick remark, I like the Metal theme, however in the settings panel the contrast is not optimal (black text on dark BG). I thought I'd bring it to your attention.

Kindest regards

**Comment by dhunt84971** [comment]
Thanks for the feedback.  I'll take a look.

**Comment by dhunt84971** [comment]
Modified the settingsSlider to respect the settingsText theme css var.

![image](https://github.com/dhunt84971/CalendarNotes/assets/674065/df5c0edf-0237-4892-bfb7-5cd379a2b65b)

**Comment by dhunt84971** [comment]
This change has been rolled into the v1.1.18 release, but TBH, there are other issues with this theme as well.  I am currently working on expanding the color theming to make it customizable.  Starting with version 1.1.17, the color theming is being gradually applied to all aspects of the application.  Eventually I hope to support themes files that can be imported.  This will give the user the ability to fully customize the colors.
